"""empty message

Revision ID: 3a6f1a7c9072
Revises: 0885403e0492
Create Date: 2023-06-05 23:08:55.704692

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '3a6f1a7c9072'
down_revision = '64ac24bef684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=os.environ.get("SCHEMA")) as batch_op:
        batch_op.add_column(sa.Column('default_channel_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=os.environ.get("SCHEMA")) as batch_op:
        batch_op.drop_column('default_channel_id')

    # ### end Alembic commands ###